---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: supporttools/rancher-cluster-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password

  - name: Test-SSH
    image: supporttools/rancher-cluster-builder:${DRONE_BUILD_NUMBER}
    pull: true
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - ssh root@172.27.7.21 "uptime"
