---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder

steps:
  - name: resolve
    image: alpine
    commands:
      - cat /etc/resolv.conf
    when:
      status: [ success, failure ]

  - name: docker-build
    image: plugins/docker
    settings:
      repo: supporttools/rancher-cluster-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
      branch: main
      event:
        include:
        - push
