---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: supporttools/rancher-cluster-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      cache_from: supporttools/rancher-cluster-builder:latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password

  - name: Run-Builder
    image: supporttools/rancher-cluster-builder:${DRONE_BUILD_NUMBER}
    pull: true
    environment:
      SSH_KEY:
        from_secret: ssh_key
      AWS_ACCESS_KEY_ID:
        from_secret: S3_ACCESSKEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: S3_SECRETKEY
      AWS_DEFAULT_REGION:
        from_secret: S3_REGION
      S3_BUCKET:
        from_secret: S3_BUCKET
    commands:
      - bash ./run.sh
