---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: supporttools/rancher-cluster-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password

  - name: Test-SSH
    image: supporttools/rancher-cluster-builder:${DRONE_BUILD_NUMBER}
    pull: true
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - ssh -q -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null root@172.27.7.21 "uptime"
      - ssh -q -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null root@172.27.7.22 "uptime"
      - ssh -q -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null root@172.27.7.23 "uptime"
