---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
  - name: Builder
    image: supporttools/rancher-cluster-builder:latest
    pull: true
    environment:
      SSH_KEY:
        from_secret: ssh_key
      AWS_ACCESS_KEY_ID:
        from_secret: S3_ACCESSKEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: S3_SECRETKEY
      AWS_DEFAULT_REGION:
        from_secret: S3_REGION
      S3_BUCKET:
        from_secret: S3_BUCKET
      S3_ENDPOINT:
        from_secret: S3_ENDPOINT
    commands:
      - bash ./run.sh

node_selector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux
  drone-runner: true