---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder

steps:
  - name: Builder
    image: supporttools/rancher-cluster-builder:latest
    pull: true
    environment:
      SSH_KEY:
        from_secret: ssh_key
      AWS_ACCESS_KEY_ID:
        from_secret: S3_ACCESSKEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: S3_SECRETKEY
      AWS_DEFAULT_REGION:
        from_secret: S3_REGION
      S3_BUCKET:
        from_secret: S3_BUCKET
    commands:
      - bash ./run.sh
